GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
username: Mathiack

# Ativando estatísticas do perfil
template: classic
base: header, activity, community, repositories, metadata

# Adicionando visualizações mais detalhadas
sections:
  activity: yes
  achievements: yes
  languages: yes
