name: Generate GitHub Metrics

on:
  schedule: # Executa a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: Mathiack
          template: classic
          base: header, repositories, activity, community, achievements
          config_timezone: America/Sao_Paulo
