# Leia a documentação completa: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Lines of Code Changed
on:
  # Atualiza a cada 12 horas
  schedule: [{ cron: "0 */12 * * *" }]
  # Permite execução manual
  workflow_dispatch:
  # Executa em push nas branches especificadas
  push: { branches: ["main", "metrics"] }

jobs:
  code-lines-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Segredo necessário para autenticação
          filename: assets/metrics.plugin.code.lines.svg # Arquivo de saída gerado
          base: header, activity, community, repositories # Seções base no layout

          # Configurações do plugin de linhas de código
          plugin_lines: yes
          plugin_lines_sections: base, repositories # Seções a serem incluídas
          plugin_lines_skipped: testing, The-Futurists_Manthan_Frontend # Repositórios a serem ignorados
          plugin_lines_repositories_limit: 4 # Limite de repositórios a incluir
