name: Discussions
on:
  # Atualiza a cada 12 horas
  schedule: [{ cron: "0 */12 * * *" }]
  # Permite execução manual
  workflow_dispatch:
  # Executa em push nas branches especificadas
  push: { branches: ["main", "metrics"] }

jobs:
  discussions-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Segredo necessário para autenticação
          filename: assets/metrics.plugin.discussions.svg # Arquivo de saída gerado
          base: "" # Layout básico, pode ser ajustado

          user: Mathiack  # Seu username no GitHub
          
          # Configurações do plugin de discussões
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8 # Limite de categorias a exibir
