# Leia a documentação completa: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Languages Activity
on:
  # Atualiza a cada 12 horas
  schedule: [{ cron: "0 */12 * * *" }]
  # Permite execução manual
  workflow_dispatch:
  # Executa em push nas branches especificadas
  push: { branches: ["main", "metrics"] }

jobs:
  language-activity-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Segredo necessário para autenticação
          filename: assets/metrics.plugin.languages.activity.svg # Arquivo de saída gerado
          base: "" # Layout básico, pode ser ajustado

          # Configurações do plugin de atividade de linguagens
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot # Linguagens a serem ignoradas
          plugin_languages_other: yes
          plugin_languages_sections: most-used # Seções a serem incluídas
          plugin_languages_details: lines, percentage # Detalhes sobre o uso
          plugin_languages_limit: 6   # Limite de linguagens a exibir (máximo 8)
          plugin_languages_analysis_timeout: 15 # Timeout de análise em minutos
