name: Leetcode
on:
  # Atualiza a cada 12 horas
  schedule: [{ cron: "0 */12 * * *" }]
  # Permite execução manual
  workflow_dispatch:
  # Executa em push nas branches especificadas
  push: { branches: ["main", "metrics"] }

jobs:
  leetcode-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.leetcode.svg  # Arquivo de saída gerado
          token: NOT_NEEDED  # O token não é necessário para o LeetCode, pois não requer autenticação
          base: ""  # Layout básico, pode ser ajustado
          user: Mathiack  # Coloque o nome do usuário aqui

          # Configurações do plugin de LeetCode
          plugin_leetcode: yes
          plugin_leetcode_user: Mathiack  # Seu nome de usuário no LeetCode
          plugin_leetcode_sections: solved, skills, recent  # Seções a serem incluídas
          plugin_leetcode_limit_recent: 5  # Limite de 5 questões recentes
          plugin_leetcode_limit_skills: 7  # Limite de 7 habilidades
