name: General Metrics
on:
  schedule: [{ cron: "0 */12 * * *" }] # Executa a cada 12 horas
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Setup Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.svg
          user: Mathiack
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_sections: breakdown
          plugin_languages_indepth: yes
          plugin_stars: yes
          plugin_topics: yes
