name: Generate GitHub Metrics

on:
  schedule: # Executa a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do conteúdo do repositório
      - name: Checkout repository content
        uses: actions/checkout@v3

      # Configura o GitHub Metrics
      - name: Setup Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Substitua pelo token configurado como segredo
          user: Mathiack
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: breakdown
          plugin_languages_indepth: yes
          plugin_stars: yes
          plugin_topics: yes
          plugin_followup: yes
