name: Notable Contributions
on:
  schedule: [{ cron: "0 */12 * * *" }]  # Executa a cada 12 horas
  workflow_dispatch:  # Permite execução manual
  push: { branches: ["main", "metrics"] }  # Executa em push nas branches especificadas

jobs:
  notable-contributions-metrics:
    runs-on: ubuntu-latest  # Executa em um ambiente Ubuntu
    steps:
      - uses: lowlighter/metrics@latest  # Usa o plugin lowlighter/metrics para gerar as métricas
        with:
          filename: assets/metrics.plugin.notable.contributions.svg  # Arquivo gerado
          token: ${{ secrets.METRICS_TOKEN }}  # Token necessário para autenticação
          base: ""  # Layout básico (pode ser ajustado)
          user: Mathiack  # Coloque o nome do usuário aqui

          # Configurações específicas para o plugin de Contribuições Notáveis
          plugin_notable: yes  # Ativa o plugin de Contribuições Notáveis
          plugin_notable_indepth: yes  # Exibe detalhes mais profundos sobre as contribuições
          plugin_notable_repositories: yes  # Inclui repositórios nas contribuições
          plugin_notable_from: all  # Inclui contribuições de qualquer repositório
          plugin_notable_types: commit, pull_request  # Considera contribuições de commits e pull requests
          plugin_notable_filter: stars:>=500  # Filtra apenas repositórios com 500 ou mais estrelas
