# Leia a documentação completa: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Notable Contributions
on:
  # Atualiza a cada 12 horas
  schedule: [{ cron: "0 */12 * * *" }]
  # Permite execução manual
  workflow_dispatch:
  # Executa em push nas branches especificadas
  push: { branches: ["main", "metrics"] }

jobs:
  notable-contributions-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.notable.contributions.svg # Arquivo de saída gerado
          token: ${{ secrets.METRICS_TOKEN }} # Token do GitHub
          base: "" # Layout básico, pode ser ajustado

          # Configurações do plugin de Contribuições Notáveis
          plugin_notable: yes
          plugin_notable_indepth: yes # Exibe detalhes mais profundos
          plugin_notable_repositories: yes # Inclui repositórios
          plugin_notable_from: all # Contribuições de qualquer repositório
          plugin_notable_types: commit, pull_request # Tipos de contribuições
          plugin_notable_filter: stars:>=500 # Filtro para repositórios com mais de 500 estrelas
