# Leia a documentação completa: https://github.com/lowlighter/metrics/blob/master/action.yml
name: Reactions
on:
  # Atualiza a cada 12 horas
  schedule: [{ cron: "0 */12 * * *" }]
  # Permite execução manual
  workflow_dispatch:
  # Executa em push nas branches especificadas
  push: { branches: ["main", "metrics"] }

jobs:
  reaction-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permissões necessárias para gravar os arquivos no repositório
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.reactions.svg  # Arquivo de saída gerado
          token: ${{ secrets.METRICS_TOKEN }}  # Token do GitHub
          base: ""  # Layout básico, pode ser ajustado

          # Configurações do plugin de Reações
          plugin_reactions: yes  # Ativa o plugin de reações
          plugin_reactions_limit: 300  # Limita a 300 reações
          plugin_reactions_details: percentage  # Exibe os detalhes em porcentagem
