name: Reactions
on:
  schedule: [{ cron: "0 */12 * * *" }]  # Executa a cada 12 horas
  workflow_dispatch:  # Permite execução manual
  push: { branches: ["main", "metrics"] }  # Executa em push nas branches especificadas

jobs:
  reaction-metrics:
    runs-on: ubuntu-latest  # Executa em um ambiente Ubuntu
    permissions:
      contents: write  # Permissões necessárias para gravar os arquivos no repositório
    steps:
      - uses: lowlighter/metrics@latest  # Usa o plugin lowlighter/metrics para gerar as métricas
        with:
          filename: assets/metrics.plugin.reactions.svg  # Arquivo gerado
          token: ${{ secrets.METRICS_TOKEN }}  # Token necessário para autenticação
          base: ""  # Layout básico (pode ser ajustado)

          # Configurações específicas para o plugin de Reações
          user: Mathiack  # Coloque o nome do usuário aqui
          plugin_reactions: yes  # Ativa o plugin de reações
          plugin_reactions_limit: 300  # Limita o número de reações a serem consideradas (300)
          plugin_reactions_details: percentage  # Exibe os detalhes das reações em porcentagem
